#pragma once

#define PLAYER_NAME_LENGTH 7
#define SECTOR_COUNT 16
#define ALL_SECTOR_COUNT SECTOR_COUNT * 2
#define SAVE_SLOT_SECTOR_COUNT 14
#define SECTOR_DATA_SIZE 3968
#define SECTOR_FOOTER_SIZE 128
#define SECTOR_UNUSED SECTOR_FOOTER_SIZE - 12
#define SECTOR_SIZE 4096
